#!/usr/bin/env python3
"""
Bundles the game source, the Roblox API mock and the test specs into a single Luau
chunk that the standalone `luau` CLI can execute.

Why a bundle instead of plain `require`?
  The Luau CLI sandboxes every required module in its own global environment. Roblox
  code reads `Instance`, `game`, `task`, `script` and friends as free globals, so a
  mock installed in one module is invisible to the next. Concatenating everything into
  one chunk gives us exactly one environment to populate.

Each module becomes:

    __modules["Shared/Core/Signal"] = function(script, require)
        <verbatim source>
    end

`script` and `require` arrive as parameters, which shadows the globals and lets
`require(script.Parent.Foo)` work unchanged. Everything else resolves against the
single chunk environment that the prologue populates with the mock.

A line map is emitted so runtime errors report real file:line locations.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "tests", ".out")
OUT = os.path.join(OUT_DIR, "bundle.luau")

SCRIPT_SUFFIXES = (".server.luau", ".client.luau")


def read(path):
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def collect_src():
    """Returns [(logical_path, absolute_path)] for every ModuleScript under src/."""
    modules = []
    src = os.path.join(ROOT, "src")
    for dirpath, dirnames, filenames in os.walk(src):
        dirnames.sort()
        for filename in sorted(filenames):
            if not filename.endswith(".luau") or filename.endswith(SCRIPT_SUFFIXES):
                continue
            full = os.path.join(dirpath, filename)
            rel = os.path.relpath(full, src).replace(os.sep, "/")
            logical = rel[: -len(".luau")]
            if logical.endswith("/init"):
                logical = logical[: -len("/init")]
            modules.append((logical, full))
    return sorted(modules)


def collect_specs():
    """Returns [(name, absolute_path)] for every *.spec.luau under tests/unit/."""
    specs = []
    unit = os.path.join(ROOT, "tests", "unit")
    if not os.path.isdir(unit):
        return specs
    for filename in sorted(os.listdir(unit)):
        if filename.endswith(".spec.luau"):
            specs.append((filename[: -len(".spec.luau")], os.path.join(unit, filename)))
    return specs


PROLOGUE = r"""--!nolint
-- AUTO-GENERATED by tools/bundle.py. Do not edit; edit the sources instead.

local __modules = {}
local __cache = {}
local __loading = {}
local __nodePaths = {}
local __pathNodes = {}

local __G = getfenv(0)
"""


def main():
    parts = [PROLOGUE]
    line_map = []  # (bundle_start_line, source_path, source_start_line)

    def current_line():
        return sum(chunk.count("\n") for chunk in parts) + 1

    def emit_module(key, path, kind):
        header = '\n__modules["%s"] = function(script, require)\n' % key
        parts.append(header)
        line_map.append((current_line(), os.path.relpath(path, ROOT), 1))
        source = read(path)
        if not source.endswith("\n"):
            source += "\n"
        parts.append(source)
        parts.append("end\n")

    # Harness modules first: the mock must exist before anything else runs.
    harness_dir = os.path.join(ROOT, "tests", "harness")
    for name in ("RobloxMock", "TestRunner"):
        emit_module("harness/" + name, os.path.join(harness_dir, name + ".luau"), "harness")

    src_modules = collect_src()
    for logical, path in src_modules:
        emit_module(logical, path, "src")

    specs = collect_specs()
    for name, path in specs:
        emit_module("spec/" + name, path, "spec")

    # ------------------------------------------------------------------ runtime
    runtime = r"""
-- ============================================================================
-- Module runtime: virtual instance tree + require shim
-- ============================================================================

local ROOT_MAP = {
	Shared = { service = "ReplicatedStorage", root = "BTS", sub = {} },
	Server = { service = "ServerScriptService", root = "BTSServer", sub = {} },
	Client = { service = "StarterPlayer", root = "BTSClient", sub = { "StarterPlayerScripts" } },
}

local function split(path)
	local segments = {}
	for segment in string.gmatch(path, "[^/]+") do
		table.insert(segments, segment)
	end
	return segments
end

local function ensureChild(parent, name, className)
	local existing = parent:FindFirstChild(name)
	if existing then
		return existing
	end
	local node = Instance.new(className or "Folder")
	node.Name = name
	node.Parent = parent
	return node
end

local function buildTree()
	local paths = {}
	for path in pairs(__modules) do
		if not string.match(path, "^harness/") and not string.match(path, "^spec/") then
			table.insert(paths, path)
		end
	end
	table.sort(paths)

	for _, path in ipairs(paths) do
		local segments = split(path)
		local mapping = ROOT_MAP[segments[1]]
		if mapping then
			local container = game:GetService(mapping.service)
			for _, sub in ipairs(mapping.sub) do
				container = ensureChild(container, sub, sub)
			end
			container = ensureChild(container, mapping.root)
			for i = 2, #segments - 1 do
				container = ensureChild(container, segments[i])
			end
			local leaf = segments[#segments]
			local node = container:FindFirstChild(leaf)
			if node then
				node.ClassName = "ModuleScript"
			else
				node = Instance.new("ModuleScript")
				node.Name = leaf
				node.Parent = container
			end
			__nodePaths[node] = path
			__pathNodes[path] = node
		end
	end
end

local function requireByPath(path, fromPath)
	local cached = __cache[path]
	if cached ~= nil then
		return cached
	end
	if __loading[path] then
		error("cyclic require: '" .. tostring(fromPath) .. "' -> '" .. path .. "'", 0)
	end
	local body = __modules[path]
	if not body then
		error("no module registered at '" .. path .. "' (required from " .. tostring(fromPath) .. ")", 0)
	end
	__loading[path] = true
	local node = __pathNodes[path]
	local result = body(node, function(target)
		return __resolveRequire(target, path)
	end)
	__loading[path] = nil
	if result == nil then
		error("module '" .. path .. "' returned nil", 0)
	end
	__cache[path] = result
	return result
end

function __resolveRequire(target, fromPath)
	if type(target) == "string" then
		return requireByPath(target, fromPath)
	end
	local path = __nodePaths[target]
	if not path then
		local label = "<unknown>"
		if type(target) == "table" then
			local ok, name = pcall(function()
				return target.Name
			end)
			if ok and name then
				label = tostring(name)
			end
		end
		error("require() target is not a bundled module: " .. label .. " (from " .. tostring(fromPath) .. ")", 0)
	end
	return requireByPath(path, fromPath)
end

-- ============================================================================
-- Bootstrap
-- ============================================================================

local Mock = __modules["harness/RobloxMock"](nil, function(t)
	return __resolveRequire(t, "harness/RobloxMock")
end)
Mock.install()
__cache["harness/RobloxMock"] = Mock

buildTree()

local Runner = requireByPath("harness/TestRunner", "bundle")
Runner.install()

__G.harness = {
	Mock = Mock,
	Runner = Runner,
	require = requireByPath,
	clearCache = function(path)
		if path then
			__cache[path] = nil
		end
	end,
}
__G.loadModule = function(path)
	return requireByPath(path, "spec")
end

-- ============================================================================
-- Spec execution
-- ============================================================================

local specNames = {}
for path in pairs(__modules) do
	if string.match(path, "^spec/") then
		table.insert(specNames, path)
	end
end
table.sort(specNames)

local loadFailures = 0
for _, path in ipairs(specNames) do
	local ok, err = pcall(requireByPath, path, "bundle")
	if not ok then
		loadFailures += 1
		print("\27[31m  Failed to load " .. path .. ": " .. tostring(err) .. "\27[0m")
	end
end

local args = { ... }
local success = Runner.run(args[1])

if loadFailures > 0 then
	success = false
end

if not success then
	error("TEST SUITE FAILED", 0)
end
"""
    parts.append(runtime)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("".join(parts))

    # Emit the line map so tools/test.sh can translate bundle line numbers.
    with open(os.path.join(OUT_DIR, "linemap.txt"), "w", encoding="utf-8") as handle:
        for bundle_line, path, source_line in line_map:
            handle.write("%d\t%s\t%d\n" % (bundle_line, path, source_line))

    print(
        "Bundle: %d source modules, %d specs -> %s"
        % (len(src_modules), len(specs), os.path.relpath(OUT, ROOT))
    )


if __name__ == "__main__":
    sys.exit(main())
